version: '3.6'
services:
  service:
    build:
      context: .
    env_file:
      - src/.env
    ports:
      - "8081:8080"
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080
  redis:
    image: redis:alpine