# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.causal_diagram_has_diagram_part_inner import CausalDiagramHasDiagramPartInner


class CausalDiagram(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CausalDiagram - a model defined in OpenAPI

        has_diagram_part: The has_diagram_part of this CausalDiagram [Optional].
        description: The description of this CausalDiagram [Optional].
        id: The id of this CausalDiagram [Optional].
        label: The label of this CausalDiagram [Optional].
        type: The type of this CausalDiagram [Optional].
    """

    has_diagram_part: Optional[List[CausalDiagramHasDiagramPartInner]] = Field(alias="hasDiagramPart", default=None)
    description: Optional[List[str]] = Field(alias="description", default=None)
    id: Optional[str] = Field(alias="id", default=None)
    label: Optional[List[str]] = Field(alias="label", default=None)
    type: Optional[List[str]] = Field(alias="type", default=None)

CausalDiagram.update_forward_refs()
