# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.variable_presentation import VariablePresentation


class Constraint(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Constraint - a model defined in OpenAPI

        description: The description of this Constraint [Optional].
        id: The id of this Constraint [Optional].
        label: The label of this Constraint [Optional].
        type: The type of this Constraint [Optional].
        has_rule: The has_rule of this Constraint [Optional].
        has_variable: The has_variable of this Constraint [Optional].
    """

    description: Optional[List[str]] = Field(alias="description", default=None)
    id: Optional[str] = Field(alias="id", default=None)
    label: Optional[List[str]] = Field(alias="label", default=None)
    type: Optional[List[str]] = Field(alias="type", default=None)
    has_rule: Optional[List[str]] = Field(alias="hasRule", default=None)
    has_variable: Optional[List[VariablePresentation]] = Field(alias="hasVariable", default=None)

Constraint.update_forward_refs()
