# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.organization import Organization
from openapi_server.models.person import Person


class EmulatorCopyrightHolderInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EmulatorCopyrightHolderInner - a model defined in OpenAPI

        identifier: The identifier of this EmulatorCopyrightHolderInner [Optional].
        website: The website of this EmulatorCopyrightHolderInner [Optional].
        description: The description of this EmulatorCopyrightHolderInner [Optional].
        id: The id of this EmulatorCopyrightHolderInner [Optional].
        label: The label of this EmulatorCopyrightHolderInner [Optional].
        type: The type of this EmulatorCopyrightHolderInner [Optional].
        email: The email of this EmulatorCopyrightHolderInner [Optional].
    """

    identifier: Optional[List[str]] = Field(alias="identifier", default=None)
    website: Optional[List[str]] = Field(alias="website", default=None)
    description: Optional[List[str]] = Field(alias="description", default=None)
    id: Optional[str] = Field(alias="id", default=None)
    label: Optional[List[str]] = Field(alias="label", default=None)
    type: Optional[List[str]] = Field(alias="type", default=None)
    email: Optional[List[str]] = Field(alias="email", default=None)

EmulatorCopyrightHolderInner.update_forward_refs()
