# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

class FundingInformation(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    FundingInformation - a model defined in OpenAPI

        description: The description of this FundingInformation [Optional].
        id: The id of this FundingInformation [Optional].
        label: The label of this FundingInformation [Optional].
        funding_source: The funding_source of this FundingInformation [Optional].
        type: The type of this FundingInformation [Optional].
        funding_grant: The funding_grant of this FundingInformation [Optional].
    """

    description: Optional[List[str]] = Field(alias="description", default=None)
    id: Optional[str] = Field(alias="id", default=None)
    label: Optional[List[str]] = Field(alias="label", default=None)
    funding_source: Optional[List[Organization]] = Field(alias="fundingSource", default=None)
    type: Optional[List[str]] = Field(alias="type", default=None)
    funding_grant: Optional[List[str]] = Field(alias="fundingGrant", default=None)

    class Config:
        arbitrary_types_allowed = True
        allow_population_by_field_name = True

    @classmethod
    def __modify_schema__(cls, field_schema):
        field_schema.update(type='string')



from openapi_server.models.organization import Organization
FundingInformation.update_forward_refs()
