# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class GeoCoordinates(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GeoCoordinates - a model defined in OpenAPI

        elevation: The elevation of this GeoCoordinates [Optional].
        latitude: The latitude of this GeoCoordinates [Optional].
        description: The description of this GeoCoordinates [Optional].
        id: The id of this GeoCoordinates [Optional].
        label: The label of this GeoCoordinates [Optional].
        type: The type of this GeoCoordinates [Optional].
        longitude: The longitude of this GeoCoordinates [Optional].
    """

    elevation: Optional[List[str]] = Field(alias="elevation", default=None)
    latitude: Optional[List[str]] = Field(alias="latitude", default=None)
    description: Optional[List[str]] = Field(alias="description", default=None)
    id: Optional[str] = Field(alias="id", default=None)
    label: Optional[List[str]] = Field(alias="label", default=None)
    type: Optional[List[str]] = Field(alias="type", default=None)
    longitude: Optional[List[str]] = Field(alias="longitude", default=None)

GeoCoordinates.update_forward_refs()
