# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.geo_coordinates import GeoCoordinates
from openapi_server.models.geo_shape import GeoShape


class RegionGeoInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RegionGeoInner - a model defined in OpenAPI

        elevation: The elevation of this RegionGeoInner [Optional].
        latitude: The latitude of this RegionGeoInner [Optional].
        description: The description of this RegionGeoInner [Optional].
        id: The id of this RegionGeoInner [Optional].
        label: The label of this RegionGeoInner [Optional].
        type: The type of this RegionGeoInner [Optional].
        longitude: The longitude of this RegionGeoInner [Optional].
        box: The box of this RegionGeoInner [Optional].
    """

    elevation: Optional[List[str]] = Field(alias="elevation", default=None)
    latitude: Optional[List[str]] = Field(alias="latitude", default=None)
    description: Optional[List[str]] = Field(alias="description", default=None)
    id: Optional[str] = Field(alias="id", default=None)
    label: Optional[List[str]] = Field(alias="label", default=None)
    type: Optional[List[str]] = Field(alias="type", default=None)
    longitude: Optional[List[str]] = Field(alias="longitude", default=None)
    box: Optional[List[str]] = Field(alias="box", default=None)

RegionGeoInner.update_forward_refs()
