# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

class Region(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Region - a model defined in OpenAPI

        geo: The geo of this Region [Optional].
        part_of: The part_of of this Region [Optional].
        description: The description of this Region [Optional].
        id: The id of this Region [Optional].
        label: The label of this Region [Optional].
        type: The type of this Region [Optional].
    """

    geo: Optional[List[RegionGeoInner]] = Field(alias="geo", default=None)
    part_of: Optional[List[Region]] = Field(alias="partOf", default=None)
    description: Optional[List[str]] = Field(alias="description", default=None)
    id: Optional[str] = Field(alias="id", default=None)
    label: Optional[List[str]] = Field(alias="label", default=None)
    type: Optional[List[str]] = Field(alias="type", default=None)

    class Config:
        arbitrary_types_allowed = True
        allow_population_by_field_name = True

    @classmethod
    def __modify_schema__(cls, field_schema):
        field_schema.update(type='string')



from openapi_server.models.region_geo_inner import RegionGeoInner
Region.update_forward_refs()
