# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class StandardVariable(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    StandardVariable - a model defined in OpenAPI

        description: The description of this StandardVariable [Optional].
        id: The id of this StandardVariable [Optional].
        label: The label of this StandardVariable [Optional].
        type: The type of this StandardVariable [Optional].
    """

    description: Optional[List[str]] = Field(alias="description", default=None)
    id: Optional[str] = Field(alias="id", default=None)
    label: Optional[List[str]] = Field(alias="label", default=None)
    type: Optional[List[str]] = Field(alias="type", default=None)

StandardVariable.update_forward_refs()
