# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class User(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    User - a model defined in OpenAPI

        password: The password of this User [Optional].
        username: The username of this User [Optional].
    """

    password: Optional[str] = Field(alias="password", default=None)
    username: Optional[str] = Field(alias="username", default=None)

User.update_forward_refs()
