name: Docker

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:

env:
  DOCKER_IMAGE_NAME: model-catalog-fastapi
  DOCKER_IMAGE_REPOSITORY: mintproject
  INFRASTRUCTURE_REPOSITORY: mintproject/mint-instances

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Create value as an environment variable
        run: |
          echo "DOCKER_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Expose value
        id: exposeValue
        run: |
          echo "::set-output name=docker_tag::${{ env.DOCKER_TAG }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          context: .
          tags: ${{ env.DOCKER_IMAGE_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
          platforms: linux/arm64

    outputs:
      docker_tag: ${{ steps.exposeValue.outputs.docker_tag }}
